### ISSUE TITLE
yaml-cpp 的存放路径

### ISSUE THREAD

**Issue by xunxuntu** [Li-Hongda/TensorRT_Inference_Demo#4]
yaml_cpp的存放路径是和 objection 、src 文件夹一个路径吗。
如果不是，那正确路径该是什么样子的。

**Comment by Li-Hongda** [comment]
是的，就在repo根目录下。

**Comment by xunxuntu** [comment]
> 是的，就在repo根目录下。

嗯嗯，跑通了，谢谢。
